# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import personnel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('notes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Notes')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Time off',
                'verbose_name_plural': 'Time off',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
                ('mark_as_read', models.BooleanField(default=False, verbose_name='Mark as read')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('country', django_countries.fields.CountryField(blank=True, default='TR', max_length=2, null=True, verbose_name='Country')),
                ('nat_id', models.CharField(max_length=12, unique=True, verbose_name='Nat ID')),
                ('gender', models.IntegerField(choices=[(1, 'Unknown'), (2, 'Female'), (3, 'Male')], default=1, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='Department')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('phone_number1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job Phone')),
                ('phone_number2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Phone')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('marital_status', models.IntegerField(choices=[(1, 'Unknown'), (2, 'Married'), (3, 'Single')], default=1, verbose_name='Marital Status')),
                ('drive_licence', models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'A'), (3, 'A1'), (4, 'A2'), (5, 'B'), (6, 'B1'), (7, 'C'), (8, 'D'), (9, 'E')], default=1, verbose_name='Drive Licence')),
                ('health_status', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('health_status'), verbose_name='Health Status')),
                ('extra_file1', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('extra_file1'), verbose_name='Extra file 1')),
                ('extra_file2', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('extra_file2'), verbose_name='Extra file 2')),
                ('extra_file3', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('extra_file3'), verbose_name='Extra file 3')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/profile.png', null=True, upload_to=personnel.models.UploadToPathAndRename('profile_pictures'), verbose_name='Profile Picture')),
                ('user_file', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('personnel_cv'), verbose_name='Personnel PDF')),
                ('notes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Notes')),
                ('cv', models.TextField(blank=True, null=True, verbose_name='CV')),
                ('total_workday', models.IntegerField(default=0, verbose_name='Total work day')),
                ('total_workhour', models.IntegerField(default=0, verbose_name='Total work hour')),
                ('total_dose', models.IntegerField(default=0, verbose_name='Total dose')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Personnel_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That personnel file name is already saved.'}, max_length=30, verbose_name='File Name')),
                ('slug', models.CharField(blank=True, max_length=30, null=True, verbose_name='Slug')),
                ('file', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('user_file'), verbose_name='File')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.Personnel', verbose_name='User')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'User file',
                'verbose_name_plural': 'User files',
            },
        ),
        migrations.CreateModel(
            name='Personnel_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That personnel type is already saved.'}, max_length=30, verbose_name='Personnel Type')),
                ('slug', models.CharField(blank=True, max_length=30, null=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fa-users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon')),
                ('color', models.CharField(default='bg-yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color')),
                ('total', models.IntegerField(default=0, verbose_name='Total user')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'User type',
                'verbose_name_plural': 'User types',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='personnel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.Personnel_type', verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
