# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0130sim')),
                ('surname', models.CharField(max_length=30, verbose_name='Soyisim')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Uyru\u011fu')),
                ('nat_id', models.CharField(max_length=12, unique=True, verbose_name='TC No')),
                ('gender', models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'Kad\u0131n'), (3, 'Erkek')], default=1, verbose_name='Cinsiyet')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='Departman')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='\xdcnvan')),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='G\xf6rev')),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+90', max_length=128, null=True, verbose_name='Telefon 1')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+90', max_length=128, null=True, verbose_name='Telefon 2')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, max_length=50, null=True, verbose_name='Adres')),
                ('marital_status', models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'Evli'), (3, 'Bekar')], default=1, verbose_name='Medeni hali')),
                ('military_situation', models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'Yapt\u0131'), (3, 'Yapmad\u0131'), (4, 'Tecilli')], default=1, verbose_name='Askerlik Durumu')),
                ('drive_licence', models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'A'), (3, 'A1'), (4, 'A2'), (5, 'B'), (6, 'B1'), (7, 'C'), (8, 'D'), (9, 'E')], default=1, verbose_name='S\xfcr\xfcc\xfc Belgesi')),
                ('health_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sa\u011fl\u0131k Durumu')),
                ('profile_picture', models.ImageField(default='profile_pictures/profile.png', null=True, upload_to='profile_pictures/', verbose_name='Profil Foto\u011fraf\u0131')),
                ('user_file', models.FileField(blank=True, null=True, upload_to='personnel_pdf/', verbose_name='Personel PDF')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='A\xe7\u0131klama')),
                ('total_workday', models.IntegerField(default=0, verbose_name='Toplam i\u015f g\xfcn\xfc')),
                ('total_workhour', models.IntegerField(default=0, verbose_name='Toplam i\u015f saati')),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
            ],
        ),
    ]
