# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='File name')),
                ('file', models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('health_status'), verbose_name='Health Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'User file',
                'verbose_name_plural': 'User files',
            },
        ),
    ]
