# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel_type',
            name='color',
            field=models.CharField(default='bg-yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='personnel_type',
            name='icon',
            field=models.CharField(default='fa-users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon'),
        ),
    ]
