# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarlaguard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='identifier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarlaguard.Identifier', verbose_name='Kart No'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
