# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel_file',
        ),
    ]
