# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20180308_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kay\u0131t Tarihi'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ldap'),
        ),
    ]
