# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 18:35
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20180308_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='\u015eirket Telefonu'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Cep Telefonu'),
        ),
    ]
