# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_delete_personnel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='extra_file1',
            field=models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('extra_file1'), verbose_name='Extra file 1'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='extra_file2',
            field=models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('extra_file2'), verbose_name='Extra file 2'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='extra_file3',
            field=models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('extra_file3'), verbose_name='Extra file 3'),
        ),
    ]
