# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20180313_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='personnel_type',
            options={'ordering': ['name'], 'verbose_name': 'User type', 'verbose_name_plural': 'User types'},
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='military_situation',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='drive_licence',
            field=models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'A'), (3, 'A1'), (4, 'A2'), (5, 'B'), (6, 'B1'), (7, 'C'), (8, 'D'), (9, 'E')], default=1, verbose_name='Drive Licence'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'Kad\u0131n'), (3, 'Erkek')], default=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='health_status',
            field=models.ImageField(blank=True, null=True, upload_to='health_status/', verbose_name='Health Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'Belirtilmemi\u015f'), (2, 'Evli'), (3, 'Bekar')], default=1, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nat_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='Nat ID'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.Personnel_type', verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Job Phone'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='total_dose',
            field=models.IntegerField(default=0, verbose_name='Total dose'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='total_workday',
            field=models.IntegerField(default=0, verbose_name='Total work day'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='total_workhour',
            field=models.IntegerField(default=0, verbose_name='Total work hour'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='personnel_pdf/', verbose_name='Personnel PDF'),
        ),
        migrations.AlterField(
            model_name='personnel_type',
            name='color',
            field=models.CharField(default='bg-yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='personnel_type',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='personnel_type',
            name='name',
            field=models.CharField(error_messages={'unique': 'That personnel type is already saved.'}, max_length=30, verbose_name='Personnel Type'),
        ),
        migrations.AlterField(
            model_name='personnel_type',
            name='slug',
            field=models.CharField(max_length=30, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='personnel_type',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total user'),
        ),
    ]
