# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20180321_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='health_status',
            field=models.FileField(blank=True, null=True, upload_to='health_status/', verbose_name='Health Status'),
        ),
    ]
