# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20180322_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='health_status',
            field=models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('health_status'), verbose_name='Health Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', null=True, upload_to=personnel.models.UploadToPathAndRename('profile_pictures'), verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('personnel_cv'), verbose_name='Personnel PDF'),
        ),
    ]
