# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 23:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_auto_20180326_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='user_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_file', to='filer.File'),
        ),
    ]
