# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_auto_20180326_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/profile.png', null=True, upload_to=personnel.models.UploadToPathAndRename('profile_pictures'), verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to=personnel.models.UploadToPathAndRename('personnel_cv'), verbose_name='Personnel PDF'),
        ),
    ]
