# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(default='01', max_length=5, verbose_name='Code')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('top_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category', verbose_name='Top Category')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='Model')),
                ('part_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Part Number')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('picture', models.ImageField(blank=True, default='item_pictures/item.png', null=True, upload_to=inventory.models.UploadToPathAndRename('item_pictures'), verbose_name='Picture')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category', verbose_name='Category')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Inventory', verbose_name='Inventory')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(default='N', max_length=5, verbose_name='Code')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Item Status',
                'verbose_name_plural': 'Item Status',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(default='01', max_length=5, verbose_name='Code')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone 1')),
                ('phone_number2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone 2')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Time-Date')),
                ('action', models.CharField(max_length=32, verbose_name='Action')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item', verbose_name='Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['timedate'],
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('code', models.CharField(default='A', max_length=5, verbose_name='Code')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location', verbose_name='Location')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Room', verbose_name='Room')),
                ('top_shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Shelf', verbose_name='Top Shelf')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('web', models.CharField(blank=True, max_length=32, null=True, verbose_name='Web')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit name')),
                ('short_name', models.CharField(max_length=5, verbose_name='slug')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ItemStatus', verbose_name='Item Status'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ItemType', verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Shelf', verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='inventory.Supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location', verbose_name='Location'),
        ),
    ]
