# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori ismi')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
                ('top_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category', verbose_name='\xdcst kategori')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Depo ismi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Malzeme Ad\u0131')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='Model')),
                ('part_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Par\xe7a Numaras\u0131')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Category', verbose_name='Kategori')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Inventory', verbose_name='Depo')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Malzeme \xc7e\u015fit ismi')),
                ('code', models.IntegerField(default=0, verbose_name='Malzeme Kodu')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Yer ismi')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Adres')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telefon')),
                ('phone_number2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
                ('action', models.CharField(max_length=32, verbose_name='Hareket')),
                ('description', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item', verbose_name='Malzeme')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tedarik\xe7i Firma')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Adres')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telefon')),
                ('web', models.CharField(blank=True, max_length=32, null=True, verbose_name='Web')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ItemType', verbose_name='Malzeme \xe7e\u015fidi'),
        ),
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='inventory.Supplier', verbose_name='Tedarik\xe7i'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location', verbose_name='Yer'),
        ),
    ]
