# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
