# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20171208_0917'),
        ('inventory', '0002_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.Personnel', verbose_name='Personel'),
        ),
    ]
