# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='olu\u015fturma tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Log Time')),
                ('action', models.CharField(default='', max_length=32, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.CharField(default='', max_length=100, verbose_name='Url')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_log_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='olu\u015fturma tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='g\xfcncelleme tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('group', models.ManyToManyField(blank=True, to='auth.Group')),
                ('owner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('top_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Statustype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon')),
                ('color', models.CharField(default='yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('percent_done', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='percent done')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('group', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Group')),
                ('owner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='Project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Statustype', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Tasktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon')),
                ('color', models.CharField(default='yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Tasktype', verbose_name='Task type'),
        ),
        migrations.AddField(
            model_name='task',
            name='top_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Task', verbose_name='Top Task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
