# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 10:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Log Time')),
                ('action', models.CharField(default='', max_length=32, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.CharField(default='', max_length=100, verbose_name='Url')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_log_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-timedate'],
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('owner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('top_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='Top Project')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Report')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Statustype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon')),
                ('color', models.CharField(default='yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Status Type',
                'verbose_name_plural': 'Status Types',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 10, 49, 34, 594131, tzinfo=utc), verbose_name='End date')),
                ('percent_done', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Percent done')),
                ('priority', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Priority')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('inchargeuser', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='People in charge')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='Project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Statustype', verbose_name='Status')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Tasktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon')),
                ('color', models.CharField(default='yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Tasktype', verbose_name='Task type'),
        ),
        migrations.AddField(
            model_name='task',
            name='top_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Task', verbose_name='Top Task'),
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Task', verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
