# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180326_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(default='', max_length=32, verbose_name='Action'),
        ),
    ]
