# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180326_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustype',
            name='color',
            field=models.CharField(default='bg-yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='statustype',
            name='icon',
            field=models.CharField(default='fa-users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='color',
            field=models.CharField(default='bg-yellow', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='icon',
            field=models.CharField(default='fa-users', help_text='<a target="_blank" href="http://fontawesome.com/icons">Icon Se\xe7enekleri</a>', max_length=20, verbose_name='Icon'),
        ),
    ]
