# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kur ismi')),
                ('short_name', models.CharField(max_length=5, verbose_name='K\u0131sa ad\u0131')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
                ('action', models.CharField(max_length=32, verbose_name='Hareket')),
                ('description', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tedarik\xe7i Firma')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Adres')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telefon')),
                ('web', models.CharField(blank=True, max_length=32, null=True, verbose_name='Web')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u0130hale Ad\u0131')),
                ('no', models.CharField(blank=True, max_length=32, null=True, verbose_name='No')),
                ('approximate_price', models.FloatField(default=0, verbose_name='Yakla\u015f\u0131k Bedel')),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ba\u015fvuru tarihi')),
                ('auction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0130hale tarihi')),
                ('auction_price', models.FloatField(default=0, verbose_name='\u0130hale Bedeli')),
                ('auction_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u0130hale No')),
                ('contract_date', models.DateField(default=django.utils.timezone.now, verbose_name='S\xf6zle\u015fme tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('deleted', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Currency', verbose_name='D\xf6viz kuru')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.Supplier', verbose_name='Y\xfcklenici')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='TenderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0130hale Durumu')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
            ],
        ),
        migrations.CreateModel(
            name='TenderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0130hale T\xfcr ismi')),
                ('code', models.IntegerField(default=0, verbose_name='\u0130hale T\xfcr Kodu')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
            ],
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.TenderStatus', verbose_name='\u0130hale durumu'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.TenderType', verbose_name='\u0130hale t\xfcr\xfc'),
        ),
        migrations.AddField(
            model_name='tender',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personel'),
        ),
        migrations.AddField(
            model_name='log',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender', verbose_name='\u0130hale'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personel'),
        ),
    ]
