# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Currency')),
                ('short_name', models.CharField(max_length=5, verbose_name='slug')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
                ('action', models.CharField(max_length=32, verbose_name='Hareket')),
                ('description', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Supplier')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone_number1', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('web', models.CharField(blank=True, max_length=32, null=True, verbose_name='Web')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tedarik\xe7i',
                'verbose_name_plural': 'Tedarik\xe7iler',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u0130hale Ad\u0131')),
                ('no', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u015eartname No')),
                ('approximate_price', models.FloatField(default=0, null=True, verbose_name='Yakla\u015f\u0131k Bedel')),
                ('apply_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ba\u015fvuru tarihi')),
                ('auction_date', models.DateField(blank=True, null=True, verbose_name='\u0130hale tarihi')),
                ('auction_time', models.TimeField(blank=True, null=True, verbose_name='\u0130hale saati')),
                ('auction_price', models.FloatField(default=0, null=True, verbose_name='\u0130hale Bedeli')),
                ('auction_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u0130hale No')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='S\xf6zle\u015fme tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('deleted', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Currency', verbose_name='D\xf6viz kuru')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Supplier', verbose_name='Y\xfcklenici')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u0130hale',
                'verbose_name_plural': '\u0130haleler',
            },
        ),
        migrations.CreateModel(
            name='Tender_end_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateField(verbose_name='Tarih')),
                ('notify', models.BooleanField(default=True, verbose_name='Mail hat\u0131rlatmas\u0131')),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender', verbose_name='\u0130hale')),
            ],
            options={
                'verbose_name': 'i\u015f teslim tarihi',
                'verbose_name_plural': 'i\u015f teslim tarihleri',
            },
        ),
        migrations.CreateModel(
            name='TenderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Currency', verbose_name='Currency')),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender', verbose_name='Tender')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Al\u0131m t\xfcr\xfc',
                'verbose_name_plural': 'Al\u0131m T\xfcrleri',
            },
        ),
        migrations.CreateModel(
            name='TenderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tender Status')),
                ('bgcolor', models.CharField(default='', help_text='<a target="_blank" href="http://basscss.com/v7/docs/background-colors/">Renk Se\xe7enekleri</a>', max_length=20, verbose_name='background')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tender Status',
                'verbose_name_plural': 'Tenders Status',
            },
        ),
        migrations.CreateModel(
            name='TenderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Code')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create date')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tender Type',
                'verbose_name_plural': 'Tender Types',
            },
        ),
        migrations.CreateModel(
            name='TravellingExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('institution', models.CharField(max_length=50, verbose_name='Institution')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Event Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Event End Date')),
                ('location', models.CharField(max_length=50, verbose_name='Event Location')),
                ('price', models.FloatField(default=0, null=True, verbose_name='Price')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Travelling Expense',
                'verbose_name_plural': 'Travelling Expenses',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit name')),
                ('short_name', models.CharField(max_length=5, verbose_name='slug')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AddField(
            model_name='tendercontent',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.TenderStatus', verbose_name='\u0130hale durumu'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.TenderType', verbose_name='\u0130hale t\xfcr\xfc'),
        ),
        migrations.AddField(
            model_name='tender',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personel'),
        ),
        migrations.AddField(
            model_name='log',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender', verbose_name='\u0130hale'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personel'),
        ),
    ]
