# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['name'], 'verbose_name': '\u0130hale', 'verbose_name_plural': '\u0130haleler'},
        ),
        migrations.AlterField(
            model_name='tendertype',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='\u0130hale T\xfcr Kodu'),
        ),
    ]
