# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_auto_20180323_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Olu\u015fturma tarihi')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='A\xe7\u0131klama')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Currency', verbose_name='Currency')),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender', verbose_name='Tender')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Al\u0131m t\xfcr\xfc',
                'verbose_name_plural': 'Al\u0131m T\xfcrleri',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit name')),
                ('short_name', models.CharField(max_length=5, verbose_name='slug')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AddField(
            model_name='tendercontent',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Unit', verbose_name='Unit'),
        ),
    ]
