# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_auto_20180129_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendertype',
            name='bgcolor',
            field=models.CharField(default='', max_length=10, verbose_name='Arkaplan rengi'),
        ),
    ]
