# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_auto_20180323_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendercontent',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tendercontent',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
    ]
