# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20180323_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendercontent',
            name='description',
        ),
        migrations.AlterField(
            model_name='tendercontent',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created date'),
        ),
    ]
