# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20180129_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender_end_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Tarih-Saat')),
            ],
            options={
                'verbose_name': 'i\u015f teslim tarihi',
                'verbose_name_plural': 'i\u015f teslim tarihleri',
            },
        ),
        migrations.AlterField(
            model_name='tender',
            name='auction_date',
            field=models.DateTimeField(verbose_name='\u0130hale tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contract_date',
            field=models.DateField(verbose_name='S\xf6zle\u015fme tarihi'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_end_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender_end_date', verbose_name='\u0130\u015f teslim tarihi'),
        ),
    ]
