# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_auto_20180214_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='tender_end_date',
        ),
        migrations.AddField(
            model_name='tender_end_date',
            name='tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.Tender', verbose_name='\u0130hale'),
        ),
    ]
