# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_auto_20180214_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender_end_date',
            name='timedate',
            field=models.DateField(verbose_name='Tarih'),
        ),
    ]
