# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_auto_20180214_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender_end_date',
            old_name='timedate',
            new_name='date',
        ),
    ]
