# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_auto_20180214_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender_end_date',
            old_name='date',
            new_name='timedate',
        ),
    ]
