# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_auto_20180214_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender_end_date',
            name='notify',
            field=models.BooleanField(default=True, verbose_name='Mail hat\u0131rlatmas\u0131'),
        ),
    ]
