# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_tender_end_date_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='apply_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Ba\u015fvuru tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='approximate_price',
            field=models.FloatField(default=0, null=True, verbose_name='Yakla\u015f\u0131k Bedel'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='auction_date',
            field=models.DateTimeField(null=True, verbose_name='\u0130hale tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='auction_price',
            field=models.FloatField(default=0, null=True, verbose_name='\u0130hale Bedeli'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contract_date',
            field=models.DateField(null=True, verbose_name='S\xf6zle\u015fme tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Supplier', verbose_name='Y\xfcklenici'),
        ),
    ]
