# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_auto_20180309_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'D\xf6viz Kuru', 'verbose_name_plural': 'D\xf6viz Kurlar\u0131'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Tedarik\xe7i', 'verbose_name_plural': 'Tedarik\xe7iler'},
        ),
        migrations.AlterModelOptions(
            name='tenderstatus',
            options={'ordering': ['name'], 'verbose_name': '\u0130hale durumu', 'verbose_name_plural': '\u0130hale durumlar\u0131'},
        ),
        migrations.AlterModelOptions(
            name='tendertype',
            options={'ordering': ['name'], 'verbose_name': 'Al\u0131m t\xfcr\xfc', 'verbose_name_plural': 'Al\u0131m T\xfcrleri'},
        ),
        migrations.AlterField(
            model_name='tendertype',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='Al\u0131m T\xfcr Kodu'),
        ),
        migrations.AlterField(
            model_name='tendertype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Al\u0131m t\xfcr\xfc'),
        ),
    ]
