# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_auto_20180310_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Tedarik\xe7i Firma'),
        ),
    ]
