# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_auto_20180310_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='auction_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0130hale saati'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='apply_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ba\u015fvuru tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='auction_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0130hale tarihi'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='S\xf6zle\u015fme tarihi'),
        ),
    ]
