# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_auto_20180313_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u015eartname No'),
        ),
    ]
