""" A django model generated with django-csvimport csvinspect
    which used OKN messytables to guess data types - may need some manual tweaks!
"""
from django.db import models


class Csvimport(models.Model):
    ''' Autogenerated model file csvimport Sat Mar 10 02:34:39 2018 '''

    name = models.(null=False, primary_key=True, blank=False)
    no = models.(null=True, blank=True)
    approximate_price = models.IntegerField(default=0, null=True, blank=True)
    apply_date = models.DateTimeField(null=True, blank=True)
    auction_date = models.DateTimeField(null=True, blank=True)
    _hale_saati = models.CharField(default='', max_length=10, blank=True)
    auction_price = models.IntegerField(default=0, null=True, blank=True)
    auction_no = models.IntegerField(default=0, null=True, blank=True)
    contract_date = models.(null=True, blank=True)
    notes = models.(null=True, blank=True)

    class Meta:
        managed = False
        db_table = u'"csvimport_"'
