# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=30, unique=True)),
                ('icon', models.CharField(blank=True, max_length=30, unique=True)),
                ('menu_type', models.IntegerField(choices=[(1, 'Sidebar'), (2, 'Main_page'), (3, 'Settings')], default=1)),
                ('top_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Menu_item')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('post_image', models.ImageField(default='post_media/post.png', null=True, upload_to='post_media/', verbose_name='Yaz\u0131 g\xf6rseli')),
                ('status', models.IntegerField(choices=[(1, 'Publish'), (2, 'Draft'), (3, 'Review'), (4, 'Deleted')], default=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='g\xfcncelleme tarihi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('int_value', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
