# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='post',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.IntegerField(choices=[(1, 'Sidebar'), (2, 'Main_page'), (3, 'Settings')], default=1),
        ),
    ]
