# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171126_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_item',
        ),
    ]
