# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171126_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='icon',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='url',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
