# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20171126_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='top_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Menu_item'),
        ),
    ]
