# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih-Saat')),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
            ],
        ),
        migrations.CreateModel(
            name='Action_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(choices=[(1, 'Enter'), (2, 'Exit'), (3, 'UndefinedCard'), (4, 'Denied'), (5, 'HealthCheck')])),
                ('level', models.IntegerField(choices=[(1, 'DEBUG'), (2, 'INFO'), (3, 'WARNING'), (4, 'ERROR')])),
                ('message', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ACP', error_messages={'unique': 'Kontrolcu ismi zaten var.'}, max_length=30, unique=True, verbose_name='Kontrolc\xfc Ad\u0131')),
                ('mac', models.CharField(error_messages={'unique': 'That identifier mac is already saved.'}, max_length=17, unique=True, verbose_name='MAC')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP adresi')),
                ('health', models.BooleanField(default=True, verbose_name='Durum')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='G\xfcncelleme tarihi')),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'That door name is already saved.'}, max_length=30, unique=True, verbose_name='Kap\u0131 ismi')),
                ('entrance_controller_pin', models.IntegerField(choices=[(1, 'Pin 1'), (2, 'Pin 2'), (3, 'Pin 3'), (4, 'Pin 4'), (5, 'Pin 5'), (6, 'Pin 6'), (7, 'Pin 7'), (8, 'Pin 8')], default=None, verbose_name='Kontrolc\xfc pin')),
                ('antipassback', models.BooleanField(default=False, verbose_name='Antipassback')),
                ('enter', models.BooleanField(default=True, verbose_name='Giri\u015f kap\u0131s\u0131')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='A\xe7\u0131klama')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='G\xfcncelleme tarihi')),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
                ('entrance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_controller', to='tarlaguard.Controller', verbose_name='Kontrolc\xfc')),
            ],
            options={
                'permissions': (('view_door', 'Can view doors'),),
            },
        ),
        migrations.CreateModel(
            name='Door_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That door group is already saved.'}, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doors', models.ManyToManyField(to='tarlaguard.Door')),
            ],
            options={
                'permissions': (('view_door_groups', 'Can view door groups'),),
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That identifier name is already saved.'}, max_length=30, verbose_name='Kart Ad\u0131')),
                ('key', models.CharField(error_messages={'unique': 'That identifier is already saved.'}, max_length=255, unique=True, verbose_name='Kart No')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('identifier_type', models.IntegerField(blank=True, choices=[(1, 'Personel'), (2, 'Ziyaret\xe7i')], null=True, verbose_name='Kart Tipi')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Olu\u015fturulma tarihi')),
                ('deleted', models.BooleanField(default=False, verbose_name='Silinmi\u015f')),
            ],
            options={
                'permissions': (('view_identifier', 'Can view identifiers'),),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarlaguard.Door')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarlaguard.Action_type', verbose_name='Hareket'),
        ),
        migrations.AddField(
            model_name='action',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarlaguard.Door', verbose_name='Kap\u0131'),
        ),
        migrations.AddField(
            model_name='action',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarlaguard.Identifier', verbose_name='Kart No'),
        ),
        migrations.AddField(
            model_name='action',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.Personnel', verbose_name='Personel'),
        ),
    ]
