# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portunes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controller',
            options={'ordering': ['name'], 'verbose_name': 'Controller', 'verbose_name_plural': 'Controllers'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portunes.Action_type', verbose_name=b'Action Type'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Date-time'),
        ),
        migrations.AlterField(
            model_name='action',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name=b'Deleted'),
        ),
        migrations.AlterField(
            model_name='action',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portunes.Door', verbose_name=b'Door'),
        ),
        migrations.AlterField(
            model_name='action',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portunes.Identifier', verbose_name=b'Identifier'),
        ),
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
